### ISSUE TITLE
Support for TFS2015.Update4

### ISSUE THREAD

**Issue by jjslagace** [ostreifel/vsts-rest-multivalue#4]
Hi,

First, thanks for all the work with this control.

I am trying to configure your control on a "On Premise" TFS2015.Update4.

On the Visual Studio Market, that version is advertised as working.  However I get an error when I run the installer:  Scope is not valid: 'vso.agentpools'

Is it supposed to work regardless of that message or it still work only with TFS2017?

Many thanks

 - Stephane

**Comment by ostreifel** [comment]
So fixing this would be fairly simple - remove the scope deploy the extension again. However this triggers, for all current users, a prompt to give permission to the extension to update since its scopes/permissions have changed instead of just updating automatically and so I will not be making this change.

If this is very important to you then fork this repro, Remove the vso.agentpools scope from [vss-extension.json](https://github.com/ostreifel/vsts-rest-multivalue/blob/master/vss-extension.json#L49) and then upload to the marketplace or your tfs instance.

Sorry for slow response I had initially forgot to turn on notifications when I had created this repository.
